apiVersion: v1
kind: Secret
metadata:
  name: schedule-api-secrets
type: Opaque
stringData:
  secret-key: "put-your-fixed-hex-or-phrase-here"
  telegram-bot-token: "8183687725:AAFnaSi3QjKBqi4SsjmYo_XMlU9EAUCVL74"
  telegram-chat-ids: "941795676,-4958028510"
